/glasses_emulator_node:
  ros__parameters:
    camera_depth: 1.0
    camera_id: 2
    draw_circle: false
    publish_freq: 100
    use_sim_time: false
    video_resolution:
      - 1920
      - 1080

/pupil_glasses_node:
  ros__parameters:
    publish_freq: 50
    draw_circle: false
    camera_depth: 1.0
    video_resolution:
      - 1920
      - 1080
    ip: "192.168.1.108"
    port: "8080"
    print_performance: False
