/glasses_emulator_node:
  ros__parameters:
    camera_id: 2
    publish_freq: 50
    draw_circle: false
    camera_depth: 1.0
    video_resolution:
      - 1920
      - 1080
    print_performance: False
    log_to_csv: False

/pupil_glasses_node:
  ros__parameters:
    publish_freq: 50
    draw_circle: false
    camera_depth: 1.0
    video_resolution:
      - 1920
      - 1080
    ip: "192.168.1.118"
    port: "8080"
    print_performance: False
    log_to_csv: True
